services:
  app:
    container_name: gorki-test-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - gorki-test

  db:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
        - db-data:/var/lib/mysql
    ports:
        - ${DB_PORT}:${DB_PORT}
    networks:
        - gorki-test

  web:
    container_name: gorki-test-web
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gorki-test

volumes:
    db-data:

networks:
    gorki-test:
        name: gorki-test
